config/routes.rb
Nreduce::Application.routes.draw do
  # Admin constraint
  admin_constraint = lambda do |request|
    request.env['warden'].authenticate? and request.env['warden'].user.admin?
  end

  namespace 'admin' do
    resources :metrics, :only => [:index]
    resources :mentors, :only => [:index, :show, :update]
    resources :users, :only => [:show, :index] do
      member do
        get 'sign_in_as'
        post 'approve'
      end
    end
    # Resque Admin
    constraints admin_constraint do
      require 'resque/server'
      require 'resque_scheduler'
      require 'resque_scheduler/server'
      mount Resque::Server.new, :at => "/resque"
    end
    # Main Admin - has logic built-in to restrict to admins
    mount RailsAdmin::Engine => '/db', :as => 'rails_admin'
  end

  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => 'sessions'}

  resources :authentications, :rsvps

  resources :conversations, :path => "messages" do
    collection do
      post 'search_startups'
      post 'mark_all_as_seen'
    end
    member do
      post 'add_message'
    end
  end

  resources :requests do
    member do
      post 'cancel'
    end
    resources :responses do
      member do
        post 'complete'
        post 'accept'
        post 'cancel'
        post 'reject'
      end
    end
  end
  get '/responses/:id/thank_you' => 'responses#thank_you', :as => 'thank_you_response'

  resources :payments do
    member do
      post 'cancel'
    end
  end

  resources :notifications, :only => [:index] do
    collection do
      post 'mark_all_as_read'
    end
  end

  resources :checkins do
    collection do
      match 'first'
    end
  end

  resources :nudges, :only => [:create, :show] do
    collection do
      post 'nudge_all_inactive'
    end
  end

  resources :investors do
    collection do
      get 'show_startup'
    end
  end

  resources :videos do
    collection do
      get 'screencast'
      get 'record'
    end
  end

  resources :calls do
    collection do
      post 'receive'
      post 'other_party_unavailable'
      post 'connected'
      post 'completed'
      post 'failed'
      get 'dial'
    end
  end

  match '/sms/receive' => 'sms#receive'

  resources :meetings, :only => [:index, :show, :edit, :update] do
    post 'message_attendees', :on => :member
    resources :meeting_messages, :only => [:index, :new, :create, :edit]
  end

  resources :awesomes, :only => [:create, :destroy]

  # for omniauth authentications with other providers
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'

  # Easy routes for auth/account stuff
  as :user do
    get '/sign_in' => "devise/sessions#new"
    get '/login' => "devise/sessions#new"
    get '/sign_up' => "registrations#new"
    match '/logout' => "devise/sessions#destroy"
  end

  get "/contact_joe" => "pages#contact_joe"
  get "/mentorsphone" => "pages#mentorsphone", :as => "mentorsphone"
  get "/home" => "pages#home", :as => "home"
  get "/nstar" => "pages#nstar", :as => "nstar"
  get "/faq" => "pages#faq", :as => "faq"
  get "/heartstartups" => "pages#heartstartups", :as => "heartstartups"
  get "/team" => "pages#team", :as => "team"
  get "/newmodel" => "pages#newmodel", :as => "newmodel"
  get "/local" => "pages#local", :as => "local"
  get "/helpproto" => "pages#helpproto", :as => "helpproto"
  get "/tos" => "pages#tos", :as => "tos"
  get "/privacy" => "pages#privacy", :as => "privacy"
  get "/testemail" => "pages#testemail", :as => "testemail"
  get "/metrics" => "pages#metrics", :as => "metrics"
  get "/success_modal" => "pages#success_modal", :as => "success_modal"
  get "/twitter_url" => "pages#twitter_url", :as => "twitter_url"
  resources :mentors, :only => [:index] do
    collection do
      post 'change_status'
      match 'search'
    end
  end

  resources :users do
    collection do
      get 'chat'
      post 'reset_hipchat_account'
    end
    member do
      match 'account_type'
      match 'complete_account'
      get 'spectator'
      post 'account_type'
      match 'welcome'
      get 'current_class'
      get 'wait_for_next_class'
      get 'change_password'
    end
    resources :notifications
  end

  match '/users/:id/onboard/:step' => "users#onboard"

  resources :comments do
    member do
      get 'reply_to'
      get 'cancel_edit'
    end
  end

  get '/tags/:context(/:term)' => "tags#search"
  
  resources :relationships, :only => [:create, :index] do
    collection do
      get 'add_teams'
      post 'skip_team'
      get 'requests'
      post 'mark_all_as_seen'
    end
    member do
      post 'approve'
      post 'reject'
    end
  end

    # Searching other startups, seeing checkins - plural resource
  resources :startups, :only => [:show, :index] do
    collection do
      get 'wait_for_next_class'
      get 'current_class'
      get 'stats'
      match 'invite'
      post 'invite_with_confirm'
      match 'search'
    end
    member do
      match 'intro_video'
      match 'before_video'
      get 'mentor_checklist'
      match 'invite_team_members'
      get 'mini_profile'
      get 'investment_profile'
    end
    resources :checkins do
      get 'latest' => "checkins#show", :checkin_id => 'latest', :on => :collection
    end
    resources :invites, :only => [:create, :destroy, :show]
    resources :ratings, :only => [:index, :new, :create]
    resources :screenshots, :only => [:create, :update, :destroy]
    resources :instruments, :except => [:index, :destroy]
    resources :questions, :except => [:update, :destroy] do
      member do
        post 'support'
        post 'answer'
      end
    end
  end

  resources :ratings, :only => [:index, :new, :create]

  resources :weekly_classes, :only => [:show] do
    member do 
      get 'update_state'
      post 'graduate'
      get 'join'
    end
  end

  # onboarding
  get '/onboard/start(/:type)' => "onboard#start", :as => :onboard_start
  get '/onboard/' => "onboard#current_step", :as => :onboard
  post '/onboard/next' => "onboard#next", :as => :onboard_next
  get '/onboard/go_to/:step' => "onboard#go_to", :as => :onboard_go_to
  get '/onboard/:id' => "onboard#show"

  resources :invites, :only => [:create, :destroy, :show] do
    get 'accept', :on => :member
  end

    # Your startup - singular resource
  resource :startup do
    member do
      post 'remove_team_member'
      get 'investment_profile'
      post 'add_invite_field'
      post 'invite_ajax'
    end
  end

  resources :posts, :only => [:index, :show] do
    post 'repost', :on => :member
  end

  match '/work_room' => 'relationships#index', :as => :work_room
  match '/board_room' => 'ratings#index', :as => :board_room
  match '/join' => 'application#join', :as => :join
  match 'startups/edit' => "startups#edit", :as => :startups_edit
  match '/mentor' => "pages#mentor", :as => :public_mentors
  match '/investor' => "pages#investor", :as => :public_investors
  match '/press' => "pages#press", :as => :public_press
  match '/tutorial' => "pages#tutorial", :as => :tutorial
  match '/why_join' => "pages#why_join", :as => :why_join
  match '/coworking_location' => 'pages#coworking_location', :as => :coworking_location
  match '/community_guidelines' => "pages#community_guidelines", :as => :community_guidelines

  # Url redirection
  match '/ciao/:url' => "application#ciao", :as => :ciao

  match '/capture_and_login' => 'application#capture_and_login', :as => :capture_and_login

  match '/nstars/:id/:startup_id' => 'demo_day#show_startup', :as => :show_startup_demo_day

  resources :demo_day, :only => [:index, :show], :path => 'nstars' do
    post 'attend', :on => :member
  end

  # Match old routes for demo day
  match '/d' => 'demo_day#index'
  match '/d/:startup_index' => 'demo_day#show_startup', :old_id => true, :id => 1

  root :to => 'pages#home'
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  acts_as_mappable
  has_many :startups
  has_many :attendees, :class_name => 'User'
  belongs_to :organizer, :class_name => 'User'
  has_many :meeting_messages
  has_many :notifications, :as => :attachable
  has_many :user_actions, :as => :attachable

  attr_accessible :location_name, :venue_name, :venue_address, :venue_url, :description,  
    :start_time, :day_of_week, :organizer_id

  validates_presence_of :location_name
  validates_uniqueness_of :location_name, :on => :create, :message => "must be unique"

  before_save :geocode_location

  def self.location_name_by_id
    Meeting.select('id, location_name').all.inject({}){|r,e| r[e.id] = e.location_name; r }
  end

  def self.select_options
    Meeting.all.map{|m| [m.location_name, m.id] }
  end

      # Returns an array with days of week and integer, ex: ['Monday', 1]
  def self.days_of_week_arr
    n = -1
    Date::DAYNAMES.map{|d| n += 1; [d, n] }
  end

      # Returns the group time as a ruby Time object using currently set time zone
  def time_with_zone
    s = "%04d" % self.start_time
    hours = s[0..1]
    mins = s[2..4]
    t = Time.now.in_time_zone(Nreduce::Application.config.time_zone)
    t = t.beginning_of_week.change(:hour => hours, :min => mins) + (self.day_of_week - 1).days
    t = t.in_time_zone(Time.zone)
  end

  def day_of_week_human
    Date::DAYNAMES[self.day_of_week.to_i]
  end

  protected

  def geocode_location
    return true if self.venue_address.blank? or (!self.venue_address_changed? and !self.lat.blank?)
    begin
      res = Meeting.geocode(self.venue_address)
      self.lat, self.lng = res.lat, res.lng
    rescue
      self.errors.add(:venue_address, "could not be geocoded")
    end
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_filter :login_required
  load_and_authorize_resource

  def index
    @current_meeting = current_user.meeting
    @meetings = @meetings.order(:location_name)
  end

  def show
    if can? :edit, @meeting
      @attendees = @meeting.attendees.order(:name).includes(:startup)
      @attendees = @attendees.sort{|a,b| (a.startup.blank? ? '' : a.startup.name) <=> (b.startup.blank? ? '' : b.startup.name) }.reverse
      @meeting_messages = @meeting.meeting_messages.ordered.limit(5)
      @can_edit = true
    end
  end

  def edit
  end

  def update
    if @meeting.update_attributes(params[:meeting])
      flash[:notice] = "Meeting has been updated."
      redirect_to @meeting
    else
      render :action => :edit
    end
  end
end

app/helpers/meeting_helper.rb
module MeetingHelper
end

app/views/meetings/_fields.html.haml
.control-group{error_css(@meeting, :location_name)}
  = f.label :location_name, :class => 'control-label'
  .controls
    = f.text_field :location_name, :class => "span4"
    = f.semantic_errors :location_name
.control-group{error_css(@meeting, :day_of_week)}
  = f.label :day_of_week, :class => 'control-label'
  .controls
    = f.select :day_of_week, options_for_select(Meeting.days_of_week_arr, @meeting.day_of_week.to_i), :class => "span4"
    = f.semantic_errors :day_of_week
.control-group{error_css(@meeting, :start_time)}
  = f.label :start_time, :class => 'control-label'
  .controls
    = f.text_field :start_time, :maxlength => 4, :placeholder => '630', :class => "span1"
    = f.semantic_errors :start_time
.control-group{error_css(@meeting, :venue_name)}
  = f.label :venue_name, :class => 'control-label'
  .controls
    = f.text_field :venue_name, :class => "span4"
    = f.semantic_errors :venue_name
.control-group{error_css(@meeting, :venue_address)}
  = f.label :venue_address, :class => 'control-label'
  .controls
    = f.text_field :venue_address, :placeholder => 'Address, City, State/Province, Zip Code, Country', :class => "span4"
    = f.semantic_errors :venue_address
.control-group{error_css(@meeting, :venue_url)}
  = f.label :venue_url, 'Google Maps URL', :class => 'control-label'
  .controls
    = f.text_field :venue_url, :class => "span4"
    = f.semantic_errors :venue_url
.control-group{error_css(@meeting, :description)}
  = f.label :description, 'Description/Comments', :class => 'control-label'
  .controls
    = f.text_area :description, :size => '80x4', :class => "span4"
    = f.semantic_errors :description
.form-actions
  = f.submit "Save", :class => "btn btn-primary btn-large"

app/views/meetings/edit.html.haml
%h2 Edit Meeting
= semantic_form_for @meeting, :html => {:class => "form-horizontal"} do |f|
  = render 'meetings/fields', :f => f

app/views/meetings/index.html.haml
- content_for :subtitle do
  Local nReduce Meetings

%h2 Local nReduce Meetings

%table
  %thead
    %th.span1{:align => 'left'} Location
    %th.span2{:align => 'left'} Starts At
    %th.span3{:align => 'left'} Venue
  %tbody
    - @meetings.all.each do |m|
      %tr
        %td.span2
          %h4= link_to m.location_name, m
        %td #{m.day_of_week_human}s at #{m.start_time}
        %td.span3= m.venue_name

app/views/meetings/show.html.haml
- content_for :subtitle do
  #{@meeting.location_name} Meeting

.row
  .span6
    %h2 #{@meeting.location_name} Meeting
  .span6{:align => 'right'}
    = link_to 'All Meetings', meetings_path
    - if @can_edit
      &nbsp;&nbsp;
      = link_to 'Edit Meeting', edit_meeting_path(@meeting), :class => 'btn'
      - if @attendees.size > 0
        &nbsp&nbsp;
        = link_to '<i class="icon icon-envelope"></i> Message Attendees'.html_safe, new_meeting_meeting_message_path(:meeting_id => @meeting.id), :class => 'btn'
.row
  .span12
    %p Meet every #{@meeting.day_of_week_human} at #{@meeting.start_time}
    %p
      %strong= @meeting.venue_name
      \-
      = @meeting.venue_url.blank? ? @meeting.venue_address : link_to(@meeting.venue_address.blank? ? 'View Details/Map' : @meeting.venue_address, @meeting.venue_url, :target => '_blank')
    - unless @meeting.organizer.blank?
      %p
        Organizer: #{@meeting.organizer.name}
        - unless @meeting.organizer.phone.blank?
          (#{@meeting.organizer.phone})
- if @organizer == true
  %hr{:style => 'margin: 20px 0 20px 0'}
  .row
    .span12
      - if @attendees.size == 0
        %h4 There aren't any attendees registered for this meeting.
      - else
        %h4 All Attendees
        %table.table
          %thead
            %tr
              %th Person
              %th Startup
              %th Twitter
              %th Phone
          %tbody
            - @attendees.each do |u|
              %tr
                %td
                  = link_to image_tag(user_avatar_url(u)), u
                  = link_to u.name, u
                %td= u.startup.blank? ? '' : link_to(u.startup.name, u.startup)
                %td= u.twitter.blank? ? '' : link_to_twitter(u.twitter)
                %td= u.phone