config/routes.rb
Nreduce::Application.routes.draw do
  # Admin constraint
  admin_constraint = lambda do |request|
    request.env['warden'].authenticate? and request.env['warden'].user.admin?
  end

  namespace 'admin' do
    resources :metrics, :only => [:index]
    resources :mentors, :only => [:index, :show, :update]
    resources :users, :only => [:show, :index] do
      member do
        get 'sign_in_as'
        post 'approve'
      end
    end
    # Resque Admin
    constraints admin_constraint do
      require 'resque/server'
      require 'resque_scheduler'
      require 'resque_scheduler/server'
      mount Resque::Server.new, :at => "/resque"
    end
    # Main Admin - has logic built-in to restrict to admins
    mount RailsAdmin::Engine => '/db', :as => 'rails_admin'
  end

  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => 'sessions'}

  resources :authentications, :rsvps

  resources :conversations, :path => "messages" do
    collection do
      post 'search_startups'
      post 'mark_all_as_seen'
    end
    member do
      post 'add_message'
    end
  end

  resources :requests do
    member do
      post 'cancel'
    end
    resources :responses do
      member do
        post 'complete'
        post 'accept'
        post 'cancel'
        post 'reject'
      end
    end
  end
  get '/responses/:id/thank_you' => 'responses#thank_you', :as => 'thank_you_response'

  resources :payments do
    member do
      post 'cancel'
    end
  end

  resources :notifications, :only => [:index] do
    collection do
      post 'mark_all_as_read'
    end
  end

  resources :checkins do
    collection do
      match 'first'
    end
  end

  resources :nudges, :only => [:create, :show] do
    collection do
      post 'nudge_all_inactive'
    end
  end

  resources :investors do
    collection do
      get 'show_startup'
    end
  end

  resources :videos do
    collection do
      get 'screencast'
      get 'record'
    end
  end

  resources :calls do
    collection do
      post 'receive'
      post 'other_party_unavailable'
      post 'connected'
      post 'completed'
      post 'failed'
      get 'dial'
    end
  end

  match '/sms/receive' => 'sms#receive'

  resources :meetings, :only => [:index, :show, :edit, :update] do
    post 'message_attendees', :on => :member
    resources :meeting_messages, :only => [:index, :new, :create, :edit]
  end

  resources :awesomes, :only => [:create, :destroy]

  # for omniauth authentications with other providers
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'

  # Easy routes for auth/account stuff
  as :user do
    get '/sign_in' => "devise/sessions#new"
    get '/login' => "devise/sessions#new"
    get '/sign_up' => "registrations#new"
    match '/logout' => "devise/sessions#destroy"
  end

  get "/contact_joe" => "pages#contact_joe"
  get "/mentorsphone" => "pages#mentorsphone", :as => "mentorsphone"
  get "/home" => "pages#home", :as => "home"
  get "/nstar" => "pages#nstar", :as => "nstar"
  get "/faq" => "pages#faq", :as => "faq"
  get "/heartstartups" => "pages#heartstartups", :as => "heartstartups"
  get "/team" => "pages#team", :as => "team"
  get "/newmodel" => "pages#newmodel", :as => "newmodel"
  get "/local" => "pages#local", :as => "local"
  get "/helpproto" => "pages#helpproto", :as => "helpproto"
  get "/tos" => "pages#tos", :as => "tos"
  get "/privacy" => "pages#privacy", :as => "privacy"
  get "/testemail" => "pages#testemail", :as => "testemail"
  get "/metrics" => "pages#metrics", :as => "metrics"
  get "/success_modal" => "pages#success_modal", :as => "success_modal"
  get "/twitter_url" => "pages#twitter_url", :as => "twitter_url"
  resources :mentors, :only => [:index] do
    collection do
      post 'change_status'
      match 'search'
    end
  end

  resources :users do
    collection do
      get 'chat'
      post 'reset_hipchat_account'
    end
    member do
      match 'account_type'
      match 'complete_account'
      get 'spectator'
      post 'account_type'
      match 'welcome'
      get 'current_class'
      get 'wait_for_next_class'
      get 'change_password'
    end
    resources :notifications
  end

  match '/users/:id/onboard/:step' => "users#onboard"

  resources :comments do
    member do
      get 'reply_to'
      get 'cancel_edit'
    end
  end

  get '/tags/:context(/:term)' => "tags#search"
  
  resources :relationships, :only => [:create, :index] do
    collection do
      get 'add_teams'
      post 'skip_team'
      get 'requests'
      post 'mark_all_as_seen'
    end
    member do
      post 'approve'
      post 'reject'
    end
  end

    # Searching other startups, seeing checkins - plural resource
  resources :startups, :only => [:show, :index] do
    collection do
      get 'wait_for_next_class'
      get 'current_class'
      get 'stats'
      match 'invite'
      post 'invite_with_confirm'
      match 'search'
    end
    member do
      match 'intro_video'
      match 'before_video'
      get 'mentor_checklist'
      match 'invite_team_members'
      get 'mini_profile'
      get 'investment_profile'
    end
    resources :checkins do
      get 'latest' => "checkins#show", :checkin_id => 'latest', :on => :collection
    end
    resources :invites, :only => [:create, :destroy, :show]
    resources :ratings, :only => [:index, :new, :create]
    resources :screenshots, :only => [:create, :update, :destroy]
    resources :instruments, :except => [:index, :destroy]
    resources :questions, :except => [:update, :destroy] do
      member do
        post 'support'
        post 'answer'
      end
    end
  end

  resources :ratings, :only => [:index, :new, :create]

  resources :weekly_classes, :only => [:show] do
    member do 
      get 'update_state'
      post 'graduate'
      get 'join'
    end
  end

  # onboarding
  get '/onboard/start(/:type)' => "onboard#start", :as => :onboard_start
  get '/onboard/' => "onboard#current_step", :as => :onboard
  post '/onboard/next' => "onboard#next", :as => :onboard_next
  get '/onboard/go_to/:step' => "onboard#go_to", :as => :onboard_go_to
  get '/onboard/:id' => "onboard#show"

  resources :invites, :only => [:create, :destroy, :show] do
    get 'accept', :on => :member
  end

    # Your startup - singular resource
  resource :startup do
    member do
      post 'remove_team_member'
      get 'investment_profile'
      post 'add_invite_field'
      post 'invite_ajax'
    end
  end

  resources :posts, :only => [:index, :show] do
    post 'repost', :on => :member
  end

  match '/work_room' => 'relationships#index', :as => :work_room
  match '/board_room' => 'ratings#index', :as => :board_room
  match '/join' => 'application#join', :as => :join
  match 'startups/edit' => "startups#edit", :as => :startups_edit
  match '/mentor' => "pages#mentor", :as => :public_mentors
  match '/investor' => "pages#investor", :as => :public_investors
  match '/press' => "pages#press", :as => :public_press
  match '/tutorial' => "pages#tutorial", :as => :tutorial
  match '/why_join' => "pages#why_join", :as => :why_join
  match '/coworking_location' => 'pages#coworking_location', :as => :coworking_location
  match '/community_guidelines' => "pages#community_guidelines", :as => :community_guidelines

  # Url redirection
  match '/ciao/:url' => "application#ciao", :as => :ciao

  match '/capture_and_login' => 'application#capture_and_login', :as => :capture_and_login

  match '/nstars/:id/:startup_id' => 'demo_day#show_startup', :as => :show_startup_demo_day

  resources :demo_day, :only => [:index, :show], :path => 'nstars' do
    post 'attend', :on => :member
  end

  # Match old routes for demo day
  match '/d' => 'demo_day#index'
  match '/d/:startup_index' => 'demo_day#show_startup', :old_id => true, :id => 1

  root :to => 'pages#home'
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :login_required
  load_and_authorize_resource :except => [:index]

  def index
    load_users_and_startups_for_conversations
    mark_all_conversations_for_current_user_as_seen
    if @conversations.present?
      @conversation = @conversations.first
      mark_conversation_as_read_for_current_user(@conversation)
    end
  end

  def show
    load_users_and_startups_for_conversations
    mark_all_conversations_for_current_user_as_seen
    respond_to do |format|
      format.js
      format.html { render :action => :index }
    end
    # Mark conversation as read for this user
    mark_conversation_as_read_for_current_user(@conversation) if @conversation.present?
  end

  def new
    @conversation.team_to_team = true # All messages by default right now are team to team
    @new_message = true
    load_users_and_startups_for_conversations unless request.xhr?
    # When you start a message to someone on a startup - need it to automatically include your co-founders?
    @conversation.messages << Message.new(:from_id => current_user.id)
    # Right now no validation on ids
    if params[:participant_ids].present?
      @conversation.participant_ids = params[:participant_ids].split('|') 
    else
      @conversation.participant_ids = [current_user.id]
    end
    if params[:startup_id].present?
      s = Startup.find_by_obfuscated_id(params[:startup_id])
      @conversation.to = "#{s.name} (Team to Team Message)"
      @conversation.to_entity = "startup_#{s.id}"
    end
    respond_to do |format|
      format.js
      format.html { render :action => :index }
    end
  end

  def create
    @conversation = Conversation.create(params[:conversation])
    if !@conversation.new_record?
      load_recent_conversations # from application controller
      respond_to do |format|
        format.js
      end
    else
      flash[:alert] = @conversation.errors.full_messages.join(', ')
      respond_to do |format|
        format.js { render :action => :new }
      end
    end
  end

  def add_message
    @conversation = Conversation.find(params[:id])
    @message = Message.new(params[:message])
    flash[:alert] = @message.errors.full_messages.join(', ') unless @message.save
    respond_to do |format|
      format.js
      format.html { render :nothing => true }
    end
  end

  def destroy
    cs = ConversationStatus.where(:user_id => current_user.id, :conversation_id => params[:id]).first
    if cs.trash!
      flash[:notice] = "The conversation has been moved to the trash."
    else
      flash[:alert] = "Sorry but that conversation couldn't be moved to the trash at this time."
    end
    redirect_to :action => :index
  end

  def search_startups
    if !current_user.entrepreneur? || params[:query].blank? || params[:query].present? && params[:query].size < 1
      render :json => [] 
      return
    end
    # Autocomplete for anyone they're connected to + nReduce
    connected_to_ids = current_user.startup.connected_to_ids('Startup') + [Startup.nreduce_id]
    #users = User.select('id, name').where(['name LIKE ?', "#{params[:query]}%"]).where("startup_id IN (#{connected_to_ids.join(',')})").limit(10)
    startups = Startup.select('id, name').where(['name LIKE ?', "#{params[:query]}%"]).where("id IN (#{connected_to_ids.join(',')})").order(:name).limit(20)
    #render :json => (users + startups).sort{|a,b| a.name <=> b.name }.map{ |e| e.is_a?(User) ? {:name => e.name, :id => "user_#{e.id}"} : {:name => "#{e.name} (Team to Team Message)", :id => "startup_#{e.id}" } }
    render :json => startups.map{|s| { :name => "#{s.name} (Team to Team Message)", :id => "startup_#{s.id}" } }
  end

  def mark_all_as_seen
    mark_all_conversations_for_current_user_as_seen
    render :nothing => true
  end

  protected

  def mark_all_conversations_for_current_user_as_seen
    current_user.conversation_statuses.unseen.each{|cs| cs.mark_as_seen! }
  end

  def mark_conversation_as_read_for_current_user(conversation)
    @conversation_statuses.each{|cs| cs.mark_as_read! if cs.conversation_id == conversation.id }
  end

  def load_users_and_startups_for_conversations
    # This is now loaded in application_controller on all actions
    #cvs = ConversationStatus.where(:user_id => current_user.id).with_folder(:inbox).includes(:conversation).order('conversations.updated_at DESC').limit(20)
    #@conversations = cvs.map{|cs| cs.conversation }

    @users_by_id = Hash.by_key(User.where(:id => @conversations.map{|c| c.participant_ids }.flatten), :id)
    #@startups_by_id = Hash.by_key(Startup.where(:id => @conversations.map{|c| c.startup_ids }.flatten), :id)
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def time_for_conversation(time) 
    if time > Time.now.beginning_of_day
      return time.strftime("%-l:%M%P")
    else
      if time > Time.now.beginning_of_week
        return time.strftime("%a")
      else
        return time.strftime("%b %-d")
      end
    end
  end

  def link_to_message_startup(startup)
    link_to '<i class="icon-envelope"></i> Message'.html_safe, new_conversation_path(:startup_id => startup.to_param), :class => 'btn'
  end

  def link_to_message_user(user)
    link_to '<i class="icon-envelope"></i> Message'.html_safe, new_conversation_path(:participant_ids => [user.id].join('|')), :class => 'btn'
  end
end

app/views/conversations/_conversation.html.haml
= div_for(conversation) do
  .head
    %h5 #{conversation.participants(current_user.id).map{|u| u.name }.to_sentence}

  .messages_wrapper
    .messages
      - conversation.messages.ordered.each do |m|
        = render 'conversations/message', :message => m

  .reply
    = form_for Message.new(:conversation_id => conversation.id, :from_id => current_user.id), :url => add_message_conversation_path(conversation), :remote => true do |f|
      = f.hidden_field :conversation_id
      = f.hidden_field :from_id
      .new_message_area
        .content= f.text_area :content, :size => '100x3', :class => 'span5', :placeholder => 'Type message here...'
        .span5.button
          .right= f.submit 'Send', :class => 'btn btn-info', :onclick => "$(this).addClass('disabled'); return true;"
        .clear

app/views/conversations/_form.html.haml
= form_for conversation, :remote => true do |f|
  .to
    %h5
      To:
      = text_field_tag 'conversation[to]', conversation.to || conversation.participants(current_user.id).map{|u| u.name }.join(', '), :class => 'conversation-to-autocomplete span4'
  - if f.object.participant_ids.present?
    - f.object.participant_ids.each do |id|
      = hidden_field_tag 'conversation[participant_ids][]', id
  = f.hidden_field :to_entity
  = f.hidden_field :team_to_team
  .messages_wrapper
    .messages
  .new_message_area
    = f.fields_for :messages do |m|
      = m.hidden_field :from_id
      .content= m.text_area :content, :size => '100x3', :class => 'span5', :placeholder => 'Type message here...'
    .span5.button
      .right= f.submit 'Send', :class => 'btn btn-info'
    .clear

app/views/conversations/_list.html.haml
- @conversation_statuses.each do |cs|
  - conversation = cs.conversation
  - latest_message = @latest_message_by_conversation[conversation.id]
  .details{:class => cs.unread? ? 'new' : '', :rel => url_for(conversation), :id => "conversation_#{conversation.id}_details"}
    .right
      .time= time_for_conversation(conversation.updated_at)
    -# If team to team show startups
    - name = pic = nil
    - if conversation.team_to_team?
      - startup = nil
      - conversation.participant_ids_without(current_user.id).each do |id|
        - if @users_by_id[id].startup_id.present? && @users_by_id[id].startup_id != current_user.startup_id
          - startup = @users_by_id[id].startup
          - pic = startup.logo_url(:small)
          - name = startup.name
    - else
      - user = @users_by_id[conversation.participant_ids_without(current_user.id).first]
      - pic = user.pic_url(:small)
      - name = conversation.participant_ids_without(current_user.id).map{|id| @users_by_id[id].present? ? @users_by_id[id].name : '' }.join(', ')
    .pic.left!= pic.blank ? '&nbsp;' : image_tag(pic)
    .left
      .names= truncate(name, :length => 26)
      .last_message= truncate(latest_message.content, :length => 32)
    .clear
    

app/views/conversations/_message.html.haml
= div_for(message) do
  - from = @users_by_id[message.from_id] || message.from
  .left.pic= link_to image_tag(from.pic_url(:small)), from
  .left.content_wrapper
    .right.time_ago= time_for_conversation(message.created_at)
    .left.from_user= link_to from.name, from
    - unless from.startup_id.blank?
      .left.from_company
        &nbsp;•&nbsp;#{link_to(from.startup.name, from.startup)}
    .clear
    .content= simple_format(h(message.content))
  .clear
  %hr/

app/views/conversations/add_message.js.haml
// Re-enable form
$("#conversation_#{@conversation.id} form :submit").removeClass('disabled');

- if @message.new_record?
  /* Error - show message */
  $("#conversation_#{@conversation.id} .new_message").prepend('#{escape_javascript(render('layouts/flash_messages'))}');

- else
  /* Add the new message to the bottom of the messages list */
  $("#conversation_#{@conversation.id} .messages").append("#{escape_javascript(render('conversations/message', :message => @message))}");
  $('.conversation textarea').autosize();

  /* Scroll message div to show new message */
  scrollConversationToBottom()
  
  /* Reset the comment form */
  $("#conversation_#{@conversation.id} #new_message")[0].reset();

  /* Highlight the new message */
  $("#message_#{@message.id}").effect("highlight", {}, 3000);

- flash.discard

app/views/conversations/create.js.haml
- if @conversation.new_record?
  /* Error - show message */
  $(".new_conversation").prepend('#{escape_javascript(render('layouts/flash_messages'))}');

- else
  /* Add the new message to the bottom of the messages list */
  $(".conversation").replaceWith("#{escape_javascript(render('conversations/conversation', :conversation => @conversation))}");

  $(".conversations .list").html("#{escape_javascript(render('conversations/list'))}");
  
  makeConversationListClickable();

- flash.discard
  

app/views/conversations/index.html.haml
.conversations
  .row
    .span3
      .list_wrapper
        .head
          .right= link_to 'New Message', new_conversation_path, :remote => true, :class => 'btn'
          .left
            %h3 Inbox
          .clear
        .list= render 'conversations/list'
    .span6
      - if @new_message == true
        .conversation= render 'conversations/form', :conversation => @conversation
      - elsif @conversations.blank?
        .conversation You haven't started any conversations yet.
      - else
        = render @conversation.present? ? @conversation : @conversations.first

app/views/conversations/new.js.haml
$(".conversation").html("#{escape_javascript(render('conversations/form', :conversation => @conversation))}");

$('#conversation_to').focus();

$('.conversation textarea').autosize();

initializeConversationAutocomplete();

app/views/conversations/show.js.haml
$(".conversation").replaceWith("#{escape_javascript(render('conversations/conversation', :conversation => @conversation))}");

$('.conversation #message_content').focus();

$(".conversations .list #conversation_#{@conversation.id}_details").removeClass('new');

scrollConversationToBottom();