config/routes.rb
Nreduce::Application.routes.draw do
  # Admin constraint
  admin_constraint = lambda do |request|
    request.env['warden'].authenticate? and request.env['warden'].user.admin?
  end

  namespace 'admin' do
    resources :metrics, :only => [:index]
    resources :mentors, :only => [:index, :show, :update]
    resources :users, :only => [:show, :index] do
      member do
        get 'sign_in_as'
        post 'approve'
      end
    end
    # Resque Admin
    constraints admin_constraint do
      require 'resque/server'
      require 'resque_scheduler'
      require 'resque_scheduler/server'
      mount Resque::Server.new, :at => "/resque"
    end
    # Main Admin - has logic built-in to restrict to admins
    mount RailsAdmin::Engine => '/db', :as => 'rails_admin'
  end

  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => 'sessions'}

  resources :authentications, :rsvps

  resources :conversations, :path => "messages" do
    collection do
      post 'search_startups'
      post 'mark_all_as_seen'
    end
    member do
      post 'add_message'
    end
  end

  resources :requests do
    member do
      post 'cancel'
    end
    resources :responses do
      member do
        post 'complete'
        post 'accept'
        post 'cancel'
        post 'reject'
      end
    end
  end
  get '/responses/:id/thank_you' => 'responses#thank_you', :as => 'thank_you_response'

  resources :payments do
    member do
      post 'cancel'
    end
  end

  resources :notifications, :only => [:index] do
    collection do
      post 'mark_all_as_read'
    end
  end

  resources :checkins do
    collection do
      match 'first'
    end
  end

  resources :nudges, :only => [:create, :show] do
    collection do
      post 'nudge_all_inactive'
    end
  end

  resources :investors do
    collection do
      get 'show_startup'
    end
  end

  resources :videos do
    collection do
      get 'screencast'
      get 'record'
    end
  end

  resources :calls do
    collection do
      post 'receive'
      post 'other_party_unavailable'
      post 'connected'
      post 'completed'
      post 'failed'
      get 'dial'
    end
  end

  match '/sms/receive' => 'sms#receive'

  resources :meetings, :only => [:index, :show, :edit, :update] do
    post 'message_attendees', :on => :member
    resources :meeting_messages, :only => [:index, :new, :create, :edit]
  end

  resources :awesomes, :only => [:create, :destroy]

  # for omniauth authentications with other providers
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'

  # Easy routes for auth/account stuff
  as :user do
    get '/sign_in' => "devise/sessions#new"
    get '/login' => "devise/sessions#new"
    get '/sign_up' => "registrations#new"
    match '/logout' => "devise/sessions#destroy"
  end

  get "/contact_joe" => "pages#contact_joe"
  get "/mentorsphone" => "pages#mentorsphone", :as => "mentorsphone"
  get "/home" => "pages#home", :as => "home"
  get "/nstar" => "pages#nstar", :as => "nstar"
  get "/faq" => "pages#faq", :as => "faq"
  get "/heartstartups" => "pages#heartstartups", :as => "heartstartups"
  get "/team" => "pages#team", :as => "team"
  get "/newmodel" => "pages#newmodel", :as => "newmodel"
  get "/local" => "pages#local", :as => "local"
  get "/helpproto" => "pages#helpproto", :as => "helpproto"
  get "/tos" => "pages#tos", :as => "tos"
  get "/privacy" => "pages#privacy", :as => "privacy"
  get "/testemail" => "pages#testemail", :as => "testemail"
  get "/metrics" => "pages#metrics", :as => "metrics"
  get "/success_modal" => "pages#success_modal", :as => "success_modal"
  get "/twitter_url" => "pages#twitter_url", :as => "twitter_url"
  resources :mentors, :only => [:index] do
    collection do
      post 'change_status'
      match 'search'
    end
  end

  resources :users do
    collection do
      get 'chat'
      post 'reset_hipchat_account'
    end
    member do
      match 'account_type'
      match 'complete_account'
      get 'spectator'
      post 'account_type'
      match 'welcome'
      get 'current_class'
      get 'wait_for_next_class'
      get 'change_password'
    end
    resources :notifications
  end

  match '/users/:id/onboard/:step' => "users#onboard"

  resources :comments do
    member do
      get 'reply_to'
      get 'cancel_edit'
    end
  end

  get '/tags/:context(/:term)' => "tags#search"
  
  resources :relationships, :only => [:create, :index] do
    collection do
      get 'add_teams'
      post 'skip_team'
      get 'requests'
      post 'mark_all_as_seen'
    end
    member do
      post 'approve'
      post 'reject'
    end
  end

    # Searching other startups, seeing checkins - plural resource
  resources :startups, :only => [:show, :index] do
    collection do
      get 'wait_for_next_class'
      get 'current_class'
      get 'stats'
      match 'invite'
      post 'invite_with_confirm'
      match 'search'
    end
    member do
      match 'intro_video'
      match 'before_video'
      get 'mentor_checklist'
      match 'invite_team_members'
      get 'mini_profile'
      get 'investment_profile'
    end
    resources :checkins do
      get 'latest' => "checkins#show", :checkin_id => 'latest', :on => :collection
    end
    resources :invites, :only => [:create, :destroy, :show]
    resources :ratings, :only => [:index, :new, :create]
    resources :screenshots, :only => [:create, :update, :destroy]
    resources :instruments, :except => [:index, :destroy]
    resources :questions, :except => [:update, :destroy] do
      member do
        post 'support'
        post 'answer'
      end
    end
  end

  resources :ratings, :only => [:index, :new, :create]

  resources :weekly_classes, :only => [:show] do
    member do 
      get 'update_state'
      post 'graduate'
      get 'join'
    end
  end

  # onboarding
  get '/onboard/start(/:type)' => "onboard#start", :as => :onboard_start
  get '/onboard/' => "onboard#current_step", :as => :onboard
  post '/onboard/next' => "onboard#next", :as => :onboard_next
  get '/onboard/go_to/:step' => "onboard#go_to", :as => :onboard_go_to
  get '/onboard/:id' => "onboard#show"

  resources :invites, :only => [:create, :destroy, :show] do
    get 'accept', :on => :member
  end

    # Your startup - singular resource
  resource :startup do
    member do
      post 'remove_team_member'
      get 'investment_profile'
      post 'add_invite_field'
      post 'invite_ajax'
    end
  end

  resources :posts, :only => [:index, :show] do
    post 'repost', :on => :member
  end

  match '/work_room' => 'relationships#index', :as => :work_room
  match '/board_room' => 'ratings#index', :as => :board_room
  match '/join' => 'application#join', :as => :join
  match 'startups/edit' => "startups#edit", :as => :startups_edit
  match '/mentor' => "pages#mentor", :as => :public_mentors
  match '/investor' => "pages#investor", :as => :public_investors
  match '/press' => "pages#press", :as => :public_press
  match '/tutorial' => "pages#tutorial", :as => :tutorial
  match '/why_join' => "pages#why_join", :as => :why_join
  match '/coworking_location' => 'pages#coworking_location', :as => :coworking_location
  match '/community_guidelines' => "pages#community_guidelines", :as => :community_guidelines

  # Url redirection
  match '/ciao/:url' => "application#ciao", :as => :ciao

  match '/capture_and_login' => 'application#capture_and_login', :as => :capture_and_login

  match '/nstars/:id/:startup_id' => 'demo_day#show_startup', :as => :show_startup_demo_day

  resources :demo_day, :only => [:index, :show], :path => 'nstars' do
    post 'attend', :on => :member
  end

  # Match old routes for demo day
  match '/d' => 'demo_day#index'
  match '/d/:startup_index' => 'demo_day#show_startup', :old_id => true, :id => 1

  root :to => 'pages#home'
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  around_filter :record_user_action
  before_filter :login_required
  before_filter :load_requested_or_users_startup, :only => [:index, :add_teams]
  load_and_authorize_resource :except => [:index, :add_teams, :skip_team]

  def index
    no_startups = false

    if current_user.mentor?
      @entity = current_user
    elsif @startup
      @entity = @startup
    end
    unless can? :read, Relationship.new(:entity => @entity)
      redirect_to current_user
      return
    end

    startup_ids = @entity.connected_to_ids('Startup')

    # Add nreduce to list if they don't have any startups
    if !current_user.entrepreneur? and startup_ids.blank?
      no_startups = true
    end
      
    # Add nReduce for everyone to see
    startup_ids << Startup.nreduce_id

    # Load startups
    @startups = Startup.where(:id => startup_ids).all

    if current_user.mentor?
      @checkins_by_startup = Checkin.current_checkin_for_startups(@startups)
    else
      @checkins_by_startup = Checkin.current_checkin_for_startups(@startups + [@startup])
    end

    # Sort by startups who have the most recent completed checkins first
    long_ago = Time.now - 100.years
    @startups.sort! do |a,b|
      a_time, b_time = long_ago, long_ago
      if !@checkins_by_startup[a.id].blank?
        a_time = @checkins_by_startup[a.id].completed_at if @checkins_by_startup[a.id].completed?
      end
      if !@checkins_by_startup[b.id].blank?
        b_time = @checkins_by_startup[b.id].completed_at if @checkins_by_startup[b.id].completed?
      end
      a_time <=> b_time
    end
    # Sort by reverse chrono order
    @startups.reverse!

    @commented_on_checkin_ids = current_user.commented_on_checkin_ids

    #@checkin_data = Checkin.participant_data_for_checkins(@checkins_by_startup.values.map{|c| c.id })

    @show_mentor_message = true if current_user.roles?(:nreduce_mentor) && no_startups == true

    @checkin_window = Checkin.in_time_window?(@startup ? @startup.checkin_offset : Checkin.default_offset) ? true : false

    store_users_by_ids(User.where(:startup_id => @startups.map{|s| s.id }))
    store_users_by_startup_id(@users_by_id.map{|id, user| user })

    if session[:checkin_completed] == true && !@startup.blank?
      @checkin_completed = true
      @number_of_consecutive_checkins = @startup.number_of_consecutive_checkins
      session[:checkin_completed] = false
    end

    if current_user.entrepreneur?
      requests = Request.ordered.includes(:responses).all
      @users_requests = requests.select{|r| r.startup_id == current_user.startup_id }
      @users_requests.sort!{|a,b| a_score = !a.closed? ? 1 : 0 <=> !b.closed? ? 1 : 0 }.reverse!
      @available_requests = requests.select{|r| r.startup_id != current_user.startup_id && !r.closed? }
      @authenticated_for_twitter = current_user.authenticated_for?('twitter')
      if !current_user.seen_help_exchange_message?
        @earn_message = true
        current_user.setup << :help_exchange
        current_user.save
      elsif params[:earn].present?
        @earn_message = true
      end
    end

    # just successfully completed request
    if session[:response_success_id].present?
      @response = Response.find(session[:response_success_id])
      session[:response_success_id] = nil
    end
  end

  def add_teams
    authorize! :add_teams, Relationship
    suggested = false
    if current_user.mentor? || current_user.investor?
      @entity = current_user
      @relationship = @entity.pending_relationships.last
      if @relationship.blank?
        flash[:notice] = "Those are all the teams that have requested to connect with you."
        redirect_to '/'
        return
      end
      @review_startup = @relationship.entity
    elsif @startup
      @entity = @startup

      # Otherwise load suggested startup
      session[:suggested_startup_ids] = @startup.generate_suggested_connections.map{|s| s.id } if session[:suggested_startup_ids].blank?

      next_id = session[:suggested_startup_ids].first if session[:suggested_startup_ids].present?

      # If there are none left to suggest
      if next_id.blank?
        flash[:notice] = "Those are all the teams you can connect to - check back next week for more teams."
        redirect_to '/'
        return
      end

      @review_startup = Startup.find(next_id)
      @relationship = Relationship.start_between(@startup, @review_startup, :startup_startup, false, true)
      suggested = true

      @startups_in_common = Relationship.startups_in_common(@review_startup, @startup)
      @num_checkins = @review_startup.checkins.count
      @num_awesomes = @review_startup.awesomes.count
      if suggested == true
        if @startup.num_active_startups >= Startup::NUM_ACTIVE_REQUIRED
          @pct_complete = 100
        else
          @num_invites_sent = @startup.initiated_relationships.pending.where(['pending_at > ?', Time.now - 1.week]).count
          @pct_complete = ((@num_invites_sent.to_f / Startup::NUM_ACTIVE_REQUIRED.to_f) * 100).round
          @num_left_to_invite = Startup::NUM_ACTIVE_REQUIRED - @num_invites_sent
        end
        @ua = {:action => UserAction.id_for('relationships_suggest'), :data => {:id => @review_startup.id}}
      else
        @ua = {:action => UserAction.id_for('relationships_show'), :data => {:id => @review_startup.id}} 
      end
    end
    # Suggested, pending relationships and invited startups
    #@suggested_startups = @startup.suggested_startups(10) unless @startup.blank?
    #@pending_relationships = @entity.pending_relationships
    #@invited_startups = current_user.sent_invites.to_startups.not_accepted.ordered

    @modal = true
  end

  def skip_team
    session[:suggested_startup_ids].delete(params[:startup_id].to_i) if params[:startup_id].present?
    flash[:notice] = "You have seen all of your suggested teams - you can continue to check out any that you didn't connect with." if session[:suggested_startup_ids].blank?
    redirect_to :action => :add_teams
  end

  def create
    @relationship.from_user_id = current_user.id
    if !@relationship.save
      flash[:alert] = @relationship.errors.full_messages.join(', ') + '.'
    elsif @relationship.pending?
      flash[:notice] = "Your connection has been requested with #{@relationship.connected_with.name}."
    elsif @relationship.approved?
      flash[:notice] = "You are already connected to #{@relationship.connected_with.name}."
    elsif @relationship.rejected?
      flash[:alert] = "Sorry, but #{@relationship.connected_with.name} has ignored your connection request."
    end
    respond_to do |format|
      format.html { redirect_to add_teams_relationships_path }
      format.js { render :action => 'update_modal' }
    end
  end

  def approve
    @relationship.message = params[:relationship][:message] if !params[:relationship].blank? and !params[:relationship][:message].blank?
    suggested = true if @relationship.suggested?
    if @relationship.approve!
      # Update rating to say investor connected if so
      unless params[:rating_id].blank?
        r = Rating.find(params[:rating_id])
        r.update_attribute('connected', true) if !r.startup_relationship.blank? && (r.startup_relationship == @relationship)
      end
      if suggested
        flash[:notice] = "Your request has been sent to #{@relationship.connected_with.name}."
      else
        flash[:notice] = "You are now connected to #{@relationship.entity.name}."
      end
    else
      flash[:alert] = "Sorry but the relationship couldn't be approved at this time."
    end
    if request.xhr?
      respond_to do |format|
        format.js { render :action => 'update_modal' }
      end
    else
      redirect_to '/'
    end
  end

  def reject
    prev_status_pending = @relationship.pending?
    prev_status_suggested = @relationship.suggested?
    if @relationship.reject_or_pass!
      removed = @relationship.entity if (@relationship.connected_with == current_user) or (!current_user.startup.blank? and (@relationship.connected_with == current_user.startup))
      removed ||= @relationship.connected_with
      # Update rating to say startup didn't connect
      unless params[:rating_id].blank?
        r = Rating.find(params[:rating_id])
        r.update_attribute('connected', false) if !r.startup_relationship.blank? && (r.startup_relationship == @relationship)
      end
      if prev_status_pending
        flash[:notice] = "You have ignored the connection request from #{removed.name}."
      elsif prev_status_suggested
        #flash[:notice] = "You have passed on that suggested connection."
      else
        flash[:notice] = "You have removed #{removed.name} from your group."
      end
    else
      flash[:alert] = "Sorry but the relationship couldn't be removed at this time."
    end
    # Save user action as removed unless it was a rejection
    @ua = {:action => UserAction.id_for('relationships_remove')} if @relationship.removed?
    if request.xhr?
      respond_to do |format|
        format.js { render :action => 'update_modal' }
      end
    else
      redirect_to '/'
    end
  end

  def mark_all_as_seen
    entity = current_user.entrepreneur? ? current_user.startup : current_user
    entity.pending_relationships.each{|r| r.mark_as_seen!(current_user.id) unless r.seen_by?(current_user.id) }
    render :nothing => true
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_buttons.html.haml
- relationship ||= nil
.relationship
  - form_id = "relationship_#{connected_with.obj_str}"
  %div{:id => "#{form_id}_details"}
    - if (!relationship.blank? and relationship.approved?) #|| entity.connected_to?(connected_with)
      - if !relationship.blank?
        = link_to 'Remove Connection'.html_safe, reject_relationship_path(:id => relationship.id), :method => :post, :confirm => "Are you sure you want to remove #{connected_with.name} as a connection?", :remote => true, :style => 'color: #777'
      - else
        = link_to 'View Profile', connected_with, :class => 'btn', :style => 'margin-bottom: 12px'
    - elsif !relationship.blank? and relationship.pending?
      / This is the person being requested
      - if relationship.connected_with == entity
        = link_to 'Not Now'.html_safe, reject_relationship_path(relationship), :class => 'btn', :method => :post, :remote => true
        &nbsp;&nbsp;
        = link_to '<i class="icon-ok icon-white"></i> Accept Connection'.html_safe, approve_relationship_path(relationship), :class => 'btn btn-success', :method => :post, :remote => true
      - else # This is the person who initiated
        = link_to '<i class="icon-remove"></i> Cancel Connection Request'.html_safe, reject_relationship_path(relationship), :class => 'btn', :method => :post, :remote => true
    - elsif !relationship.blank? and relationship.suggested?
      /= link_to '<i class="icon-refresh"></i> Pass'.html_safe, reject_relationship_path(relationship), :class => 'btn btn-large', :method => :post
      /&nbsp;&nbsp;
      = link_to '<i class="icon-ok icon-white"></i> Connect'.html_safe, '#', :onclick => "$('##{form_id}').modal(); return false;", :class => 'btn btn-success'
    - elsif user_signed_in? # and Relationship.can_connect?(entity, connected_with)
      = link_to('Connect', '#', :onclick => "$('##{form_id}').modal(); return false;", :class => 'btn btn-info')
    - relationship ||= Relationship.new(:entity => entity, :connected_with => connected_with)
    / Clear out message if it's a suggested relationship
    - relationship.message = nil if relationship && relationship.suggested?
  = render 'relationships/request_modal', :relationship => relationship, :form_id => form_id, :connected_with => connected_with, :entity => entity

app/views/relationships/index_old.html.haml
- content_for :subtitle do
  Work Room

%h1.hide Work Room

- if current_user.entrepreneur? && current_user.startup_id.present?
  = render 'startups/countdown_and_checkin', :startup => current_user.startup

.relationships
  .row.teams{:style => 'padding-top: 20px;'}
    - c = 0
    - # Add 1 for watercooler
    - num = @active_startups.size
    - @active_startups.each do |s|
      - if s == :joining_soon
        .team.span3{:align => 'center'}
          .top{:align => 'center'}
            .background
              .startup_spinner
          .bottom{:align => 'center'}
            %h3 Joining Soon
      - else
        - owner = (@startup && (s.id == @startup.id))
        - current_checkin = @checkins_by_startup[s.id]
        - this_startup_url = (current_checkin and current_checkin.completed?) ? latest_startup_checkins_url(s) : startup_url(s)
        - logo_path = s.logo_url(:square)
        .team.span3{:align => 'center'}
          .top{:align => 'center', :onclick => "window.location = '#{this_startup_url}';"}
            .background{:style => "background-image: url('#{logo_path}'); cursor: pointer;"} &nbsp;
            .status.btn-group{:align => 'center', 'data-toggle' => 'buttons-checkbox'}
              %button.btn{:href => '#', :class => ((current_checkin and current_checkin.submitted?) ? 'btn-success' : 'disabled active')} Before
              %button.btn{:href => '#', :class => ((current_checkin and current_checkin.completed?) ? 'btn-success' : 'disabled active')} After
            .members{:align => 'center'}
              - @users_by_startup_id[s.id].shuffle.first(3).each do |tm|
                .inline-block{:style => 'margin-left: 4px'}= image_tag(user_avatar_url(tm), :title => tm.name, :style => 'width: 50px; height: 50px;')
          .bottom{:align => 'center'}
            %h3= link_to owner ? 'You' : truncate(s.name, :length => 20), startup_path(s)
            - if current_checkin and current_checkin.completed?
              - if owner
                = link_to 'Respond to Feedback', latest_startup_checkins_path(s), :class => 'btn btn-success'
              - elsif @commented_on_checkin_ids.include?(current_checkin.id)
                = link_to '<i class="icon icon-ok"></i> Feedback Given'.html_safe, latest_startup_checkins_path(s), :class => 'btn'
              - else
                = link_to 'Give Feedback', latest_startup_checkins_path(s), :class => 'btn btn-success'
              %p
                %small
                  &nbsp;
                  - if current_checkin.awesome_count > 0
                    = pluralize(current_checkin.awesome_count, 'awesome')
                  - if current_checkin.awesome_count > 0 and current_checkin.comment_count > 0
                    &nbsp;-&nbsp;
                  - if current_checkin.comment_count > 0
                    = pluralize(current_checkin.comment_count, 'comment')
                  &nbsp;
            - elsif current_checkin.present? && !@checkin_window
              = link_to 'View Goal', startup_checkin_path(s, current_checkin), :class => 'btn btn-success'
              - if current_checkin.comment_count > 0
                %p
                  %small= pluralize(current_checkin.comment_count, 'comment')
            - if @checkin_window && !owner and (current_checkin.blank? or (current_checkin and !current_checkin.completed?))
              = form_for Nudge.new(:startup_id => s.id), :html => {:id => "new_nudge_startup_#{s.id}"} do |f|
                = f.hidden_field :startup_id
                = link_to '<i class="icon-hand-left icon"></i> Nudge'.html_safe, '#', :title => "Nudge #{s.name} to complete their check-in with an email!", :onclick => "$('#new_nudge_startup_#{s.id}').submit();", :class => 'btn'
      - c += 1
      -# Show water cooler on far right
      - if (num < 3 && c == num) || c == 3
        -# Add empty elements if needed
        - if num < 3
          - [num..3].each do
            .span3.team{:align => 'center'}
              .top
              .bottom
              - c += 1
        .span3.team{:align => 'center'}
          .top{:align => 'center', :onclick => "window.location = '#{posts_path}';"}
            .background{:style => "background-image: url('#{image_path('napp_bg.png')}'); cursor: pointer; border: 2px solid #fff; opacity: 1.0;"}
            %div{:style => "background: url('#{image_path('watercooler.png')}') no-repeat; height: 200px; width: 200px;"}
          .bottom{:align => 'center'}
            %h3= link_to 'Water Cooler', posts_path
            = link_to 'Meet Cool People', posts_path, :class => 'btn'
        - if c == 3
          .clear
        - c += 1
      - elsif c != 0 and c % 4 == 0
        .clear
      
      
  .center
    - nreduce_id = Startup.nreduce_obfuscated_id
    - if current_user.entrepreneur? and !nreduce_id.blank?
      .inline-block{:style => 'margin-right: 25px'}
        %h3= link_to 'View nReduce\'s Latest Checkin', latest_startup_checkins_path(:startup_id => nreduce_id)
    .inline-block{:style => 'margin-left: 25px'}
      %h3= link_to 'View Your Teams on Vacation', '#', :onclick => "$('.inactive_teams').toggle(); return false;"
    .clear
  .inactive_teams.hide
    .row
      .span2
        %p
      .span6
        %p Teams who take time off or do not check in for 2 or more weeks go on vacation. When they come back to work they will appear in your active teams. You are still more than welcome to nudge them :)
      .span2
        = link_to 'Nudge All', nudge_all_inactive_nudges_path, :class => 'btn btn-success btn-large', :method => :post
    - c = 0
    .row.teams{:style => 'padding-top: 20px;'}
      - @inactive_startups.each do |s|
        - this_startup_url = startup_url(s)
        - logo_path = s.logo_url(:square)
        .team.span3{:align => 'center'}
          .top{:align => 'center', :onclick => "window.location = '#{this_startup_url}';"}
            .background{:style => "background-image: url('#{logo_path}'); cursor: pointer;"} &nbsp;
            .members{:align => 'center'}
              - team_members = @users_by_startup_id[s.id] || s.team_members
              - team_members.shuffle.first(3).each do |tm|
                .inline-block{:style => 'margin-left: 4px'}= image_tag(user_avatar_url(tm), :title => tm.name, :style => 'width: 50px; height: 50px;')
          .bottom{:align => 'center'}
            %h3= link_to truncate(s.name, :length => 20), startup_path(s)
            = form_for Nudge.new(:startup_id => s.id), :html => {:id => "new_nudge_startup_#{s.id}"} do |f|
              = f.hidden_field :startup_id
              = link_to '<i class="icon-hand-left icon"></i> Nudge'.html_safe, '#', :title => "Nudge #{s.name} to complete their check-in with an email!", :onclick => "$('#new_nudge_startup_#{s.id}').submit();", :class => 'btn'
        - c += 1
        - if c != 0 and c % 4 == 0
          .clear
      .clear

  - if @show_mentor_message
    %hr{:style => 'margin: 20px 0 20px 0;'}
    .row
      .span3
        &nbsp;
      .span6
        %h3 Welcome to the nReduce Mentor network!  
        %br/ 
        %p Startups earn the ability to access the mentor network with 1-3 months of hard work on nReduce. Once they earn access they can contact one mentor per week. If you are contacted by a startup for a mentorship, you will receive an email and the startup will appear above. You can then learn about the startup and decide if you would like to mentor them.
        %p If you decide to mentor the startup, you will be notified about their weekly progress and be able to give feedback and advice.  To help you get familiar with the system, we have connected you with team nReduce.
        %br/ 
        %p The window for posting their weekly progress opens at 4pm PST on Mondays and closes at 4 PM PST on Tuesdays.  Once one of your startups posts their after video for the week, you will be notifed by email and a "Give Feedback" button will appear below their startup square. Simply click this button to access their checkin and give feedback.
        %p If it is after 4pm PST on Monday and one of your teams hasn't posted their after video, you will see a "Nudge" button that will send them a message saying that you are waiting to give them feedback.
        %br/ 
        %p If you are mentoring other startups outside of nReduce, you can invite them to join nReduce so that you can mentor all of your startups in one place. Simply click the invite button above and enter their startup name and email to do so.
        %br/ 
        %p Mentorship is essential for startups to succeed and we are very grateful that you are willing to help these great entrepreneurs build amazing companies.
        %br/ 
        %p
          Please contact me if you have any questions:
          = mail_to 'joe@nreduce.com'
          c: +1-415-259-8215
        %br/ 
        %p Best, 
        %b -Joe
        %br/
        %p
          P.S. To meet your fellow nReduce mentors who are also passionate about helping startups, click the
          = link_to 'board room', board_room_path
          in the menu bar!
      .span3
        &nbsp;

- if @checkin_completed == true
  #checkin_completed.modal.hide
    .modal-body.center{:align => 'center'}
      - if @number_of_consecutive_checkins > 1
        %p You have completed #{@number_of_consecutive_checkins} consecutive checkins.
      - else
        %p You have completed your checkin.
      .right{:style => 'margin-right: -15px'}= image_tag 'hand_silhouette.png', :width => 270, :height => 220
      .right{:style => 'width: 250px; height: 270px; position: relative;'}
        %div{:style => 'position: absolute; top: 30%; right: 30%; height: 270px;'}
          %h2{:style => 'font-size: 50px; line-height: 50px'}
            Way to
            %br/
            do it!
      
      .clear

      %a.btn.btn-success.btn-large{:href => '#', 'data-dismiss' => 'modal'} Keep Working
  :javascript
    $('#checkin_completed').modal();