config/routes.rb
Nreduce::Application.routes.draw do
  # Admin constraint
  admin_constraint = lambda do |request|
    request.env['warden'].authenticate? and request.env['warden'].user.admin?
  end

  namespace 'admin' do
    resources :metrics, :only => [:index]
    resources :mentors, :only => [:index, :show, :update]
    resources :users, :only => [:show, :index] do
      member do
        get 'sign_in_as'
        post 'approve'
      end
    end
    # Resque Admin
    constraints admin_constraint do
      require 'resque/server'
      require 'resque_scheduler'
      require 'resque_scheduler/server'
      mount Resque::Server.new, :at => "/resque"
    end
    # Main Admin - has logic built-in to restrict to admins
    mount RailsAdmin::Engine => '/db', :as => 'rails_admin'
  end

  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => 'sessions'}

  resources :authentications, :rsvps

  resources :conversations, :path => "messages" do
    collection do
      post 'search_startups'
      post 'mark_all_as_seen'
    end
    member do
      post 'add_message'
    end
  end

  resources :requests do
    member do
      post 'cancel'
    end
    resources :responses do
      member do
        post 'complete'
        post 'accept'
        post 'cancel'
        post 'reject'
      end
    end
  end
  get '/responses/:id/thank_you' => 'responses#thank_you', :as => 'thank_you_response'

  resources :payments do
    member do
      post 'cancel'
    end
  end

  resources :notifications, :only => [:index] do
    collection do
      post 'mark_all_as_read'
    end
  end

  resources :checkins do
    collection do
      match 'first'
    end
  end

  resources :nudges, :only => [:create, :show] do
    collection do
      post 'nudge_all_inactive'
    end
  end

  resources :investors do
    collection do
      get 'show_startup'
    end
  end

  resources :videos do
    collection do
      get 'screencast'
      get 'record'
    end
  end

  resources :calls do
    collection do
      post 'receive'
      post 'other_party_unavailable'
      post 'connected'
      post 'completed'
      post 'failed'
      get 'dial'
    end
  end

  match '/sms/receive' => 'sms#receive'

  resources :meetings, :only => [:index, :show, :edit, :update] do
    post 'message_attendees', :on => :member
    resources :meeting_messages, :only => [:index, :new, :create, :edit]
  end

  resources :awesomes, :only => [:create, :destroy]

  # for omniauth authentications with other providers
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'

  # Easy routes for auth/account stuff
  as :user do
    get '/sign_in' => "devise/sessions#new"
    get '/login' => "devise/sessions#new"
    get '/sign_up' => "registrations#new"
    match '/logout' => "devise/sessions#destroy"
  end

  get "/contact_joe" => "pages#contact_joe"
  get "/mentorsphone" => "pages#mentorsphone", :as => "mentorsphone"
  get "/home" => "pages#home", :as => "home"
  get "/nstar" => "pages#nstar", :as => "nstar"
  get "/faq" => "pages#faq", :as => "faq"
  get "/heartstartups" => "pages#heartstartups", :as => "heartstartups"
  get "/team" => "pages#team", :as => "team"
  get "/newmodel" => "pages#newmodel", :as => "newmodel"
  get "/local" => "pages#local", :as => "local"
  get "/helpproto" => "pages#helpproto", :as => "helpproto"
  get "/tos" => "pages#tos", :as => "tos"
  get "/privacy" => "pages#privacy", :as => "privacy"
  get "/testemail" => "pages#testemail", :as => "testemail"
  get "/metrics" => "pages#metrics", :as => "metrics"
  get "/success_modal" => "pages#success_modal", :as => "success_modal"
  get "/twitter_url" => "pages#twitter_url", :as => "twitter_url"
  resources :mentors, :only => [:index] do
    collection do
      post 'change_status'
      match 'search'
    end
  end

  resources :users do
    collection do
      get 'chat'
      post 'reset_hipchat_account'
    end
    member do
      match 'account_type'
      match 'complete_account'
      get 'spectator'
      post 'account_type'
      match 'welcome'
      get 'current_class'
      get 'wait_for_next_class'
      get 'change_password'
    end
    resources :notifications
  end

  match '/users/:id/onboard/:step' => "users#onboard"

  resources :comments do
    member do
      get 'reply_to'
      get 'cancel_edit'
    end
  end

  get '/tags/:context(/:term)' => "tags#search"
  
  resources :relationships, :only => [:create, :index] do
    collection do
      get 'add_teams'
      post 'skip_team'
      get 'requests'
      post 'mark_all_as_seen'
    end
    member do
      post 'approve'
      post 'reject'
    end
  end

    # Searching other startups, seeing checkins - plural resource
  resources :startups, :only => [:show, :index] do
    collection do
      get 'wait_for_next_class'
      get 'current_class'
      get 'stats'
      match 'invite'
      post 'invite_with_confirm'
      match 'search'
    end
    member do
      match 'intro_video'
      match 'before_video'
      get 'mentor_checklist'
      match 'invite_team_members'
      get 'mini_profile'
      get 'investment_profile'
    end
    resources :checkins do
      get 'latest' => "checkins#show", :checkin_id => 'latest', :on => :collection
    end
    resources :invites, :only => [:create, :destroy, :show]
    resources :ratings, :only => [:index, :new, :create]
    resources :screenshots, :only => [:create, :update, :destroy]
    resources :instruments, :except => [:index, :destroy]
    resources :questions, :except => [:update, :destroy] do
      member do
        post 'support'
        post 'answer'
      end
    end
  end

  resources :ratings, :only => [:index, :new, :create]

  resources :weekly_classes, :only => [:show] do
    member do 
      get 'update_state'
      post 'graduate'
      get 'join'
    end
  end

  # onboarding
  get '/onboard/start(/:type)' => "onboard#start", :as => :onboard_start
  get '/onboard/' => "onboard#current_step", :as => :onboard
  post '/onboard/next' => "onboard#next", :as => :onboard_next
  get '/onboard/go_to/:step' => "onboard#go_to", :as => :onboard_go_to
  get '/onboard/:id' => "onboard#show"

  resources :invites, :only => [:create, :destroy, :show] do
    get 'accept', :on => :member
  end

    # Your startup - singular resource
  resource :startup do
    member do
      post 'remove_team_member'
      get 'investment_profile'
      post 'add_invite_field'
      post 'invite_ajax'
    end
  end

  resources :posts, :only => [:index, :show] do
    post 'repost', :on => :member
  end

  match '/work_room' => 'relationships#index', :as => :work_room
  match '/board_room' => 'ratings#index', :as => :board_room
  match '/join' => 'application#join', :as => :join
  match 'startups/edit' => "startups#edit", :as => :startups_edit
  match '/mentor' => "pages#mentor", :as => :public_mentors
  match '/investor' => "pages#investor", :as => :public_investors
  match '/press' => "pages#press", :as => :public_press
  match '/tutorial' => "pages#tutorial", :as => :tutorial
  match '/why_join' => "pages#why_join", :as => :why_join
  match '/coworking_location' => 'pages#coworking_location', :as => :coworking_location
  match '/community_guidelines' => "pages#community_guidelines", :as => :community_guidelines

  # Url redirection
  match '/ciao/:url' => "application#ciao", :as => :ciao

  match '/capture_and_login' => 'application#capture_and_login', :as => :capture_and_login

  match '/nstars/:id/:startup_id' => 'demo_day#show_startup', :as => :show_startup_demo_day

  resources :demo_day, :only => [:index, :show], :path => 'nstars' do
    post 'attend', :on => :member
  end

  # Match old routes for demo day
  match '/d' => 'demo_day#index'
  match '/d/:startup_index' => 'demo_day#show_startup', :old_id => true, :id => 1

  root :to => 'pages#home'
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :startup
  has_many :awesomes, :as => :awsm, :dependent => :destroy

  attr_accessible :explanation, :feedback, :interested, :startup_id, :contact_in, :weakest_element, :connected

  FEEDBACK_OPTIONS = [:team, :idea, :traction, :market]

  bitmask :feedback, :as => Rating::FEEDBACK_OPTIONS

  validates_presence_of :startup_id
  validates_presence_of :user_id
  validates_presence_of :contact_in
  validates_presence_of :weakest_element
  validate :relationship_exists
  validate :investor_can_connect

  before_validation :set_interested_from_contact_in
  before_create :change_suggested_relationship_state

  scope :ordered, order('created_at DESC')

  CONTACT_IN_NEVER = 1
  CONTACT_IN_NOW = 5

  def self.weakest_element_labels
    {
      1 => 'Team',
      2 => 'Market',
      3 => 'Traction',
      4 => 'Product',
      5 => 'Other'
    }
  end

  def self.contact_in_labels(extended = false)
    if extended
      { 1 => "Don't show me this startup again",
        2 => 'Show me again in 6 months and I might be interested',
        3 => 'Show me again in 3 months and I might be interested',
        4 => 'Show me again in 1 month and I might be interested',
        5 => 'Please introduce me today'
      }
    else
      { 1 => 'Not a fit',
        2 => '6 months',
        3 => '3 months',
        4 => '1 month',
        5 => 'Now'
      }
    end
  end

  def contact_now?
    self.contact_in == CONTACT_IN_NOW
  end

  def contact_never?
    self.contact_in == CONTACT_IN_NEVER
  end

  def contact_in_desc
    return nil if self.contact_in.blank?
    Rating.contact_in_labels[self.contact_in] unless Rating.contact_in_labels[self.contact_in].blank?
  end

  def weakest_element_desc
    return nil if self.weakest_element.blank?
    Rating.weakest_element_labels[self.weakest_element] unless Rating.weakest_element_labels[self.weakest_element].blank?
  end

  # Takes an array of ratings and returns for column provided, either :contact_in or :weakest_element
  # eg: [['Traction', 5], ['Market', 4]] - used in charts
  def self.chart_data_from_ratings(ratings, column)
    investor_ratings = {}
    mentor_ratings = {}
    labels = Rating.send("#{column}_labels".to_sym)

    # Set it up so all values are represented
    labels.each{|id, label| investor_ratings[id] = 0; mentor_ratings[id] = 0 }

    # Split up ratings between investors and mentors
    ratings.each do |r|
      if r.user.investor?
        investor_ratings[r.send(column)] += 1
      elsif r.user.mentor?
        mentor_ratings[r.send(column)] += 1
      end
    end

    {
      :categories => labels.values, 
      :series =>
        {
          'Investor' => investor_ratings.sort.map{|k,v| v }, 
          'Mentor' => mentor_ratings.sort.map{|k,v| v }
        }
    }
  end

  # Finds the relationship that exists between the startup and investor involved in this rating
  def startup_relationship
    Relationship.between(self.user, self.startup)
  end

  protected

  def set_interested_from_contact_in
    self.interested = true if self.contact_in == CONTACT_IN_NOW
    true
  end

  def investor_can_connect
    if self.interested? # only check if they want to connect
      unless self.user.can_connect_with_startups?
        self.errors.add(:startup_id, 'you have reached your limit - please upgrade your account to connect to more startups')
        return false
      end
    end
    true
  end

  def relationship_exists
    if self.new_record?
      rel = self.startup_relationship
      if rel.blank? || (!rel.blank? and !rel.suggested?)
        self.errors.add(:startup_id, "has already been rated by you.")
        return false
      end
    end
    true
  end

  # Sets suggested relationship to pending if interested, or passed if they pass
  def change_suggested_relationship_state
    if self.new_record?
      rel = self.startup_relationship
      if self.interested?
        rel.approve! # turns it to pending state
      else
        rel.reject_or_pass! # sets it as passed
      end
    end
    true
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  #around_filter :record_user_action, :only => [:create]
  before_filter :login_required
  load_and_authorize_resource
  
  def index
    if current_user.entrepreneur?
      @startup = current_user.startup
      if current_user.startup.can_access_mentors_and_investors?
        @ratings = @startup.ratings.ordered
        unless @ratings.blank?
          @weakest_element_data = Rating.chart_data_from_ratings(@ratings, :weakest_element)
          @contact_in_data = Rating.chart_data_from_ratings(@ratings, :contact_in)
        end
      else
        @num_mentors = User.with_roles(:nreduce_mentor).count
        @startup_elements = @startup.investor_mentor_elements
        @previous_checkin = @startup.previous_checkin
      end
      render :action => :entrepreneur
    else
      authorize! :see_ratings_page, current_user
      startups = current_user.connected_to
      startups = Startup.limit(10).all + [Startup.find(319)] if Rails.env.development?
      @checkins_by_week = Checkin.for_startups_by_week(startups, 20)
      @startups_by_id =  Hash.by_key(startups, :id)
      @total_num_ratings = current_user.ratings.count
      @total_value_adds = current_user.ratings_awesomes.count
      if current_user.investor?
        @user_type = 'Investor'
        @total_people = User.with_roles(:investor).count 
      elsif current_user.mentor?
        @user_type = 'Mentor'
        @total_people = User.with_roles(:nreduce_mentor).count
      end
      # Will grab four weeks of checkins for these startups
      calculate_suggested_startup_completeness
      render :action => :mentor_investor
    end
  end

  def new
    authorize! :investor_mentor_connect_with_startups, current_user
    @startup = current_user.suggested_startups(1).first

    if @startup.blank?
      flash[:notice] = "Thanks, you've reviewed all of the startups currently available to you."
      redirect_to :action => :index
      return
    end

    calculate_suggested_startup_completeness

    @checkin_history = Checkin.history_for_startup(@startup)
    @screenshots = @startup.screenshots.ordered

    @rating.startup = @startup
    @rating.interested = false

    @instrument = @startup.instruments.first
    @measurements = @instrument.measurements.ordered_asc.all unless @instrument.blank?

    last_checkin = @startup.checkins.ordered.first
    @checkins = last_checkin.present? ? [last_checkin] : []
   
    @videos = @startup.investor_videos #User.find(810).videos.vimeod.all
    @vimeo_js = true
  end

  def create
    @rating.user = current_user
    if @rating.save
      #flash[:notice] = "Your rating has been stored!"
      # They are done rating startups
      if params[:commit].match(/stop/i) != nil
        @redirect_to = ratings_path
      else # They want to continue
        # Check if they are above their limit
        if current_user.can_connect_with_startups?
          @redirect_to = new_rating_path
        else
          flash[:alert] = "You've already contacted a startup this week, please come back later or upgrade your account to connect with more startups."
          @redirect_to = ratings_path
        end
      end
      # JS will render page that redirects to url
      respond_to do |format|
        format.js { render 'layouts/redirect_to' }
        format.html { redirect_to @redirect_to }
      end
    else
      respond_to do |format|
        format.js { render :action => :edit }
        format.html { render :nothing => true }
      end
    end
  end

  protected

  def calculate_suggested_startup_completeness
    @total_suggested_startups = User::INVESTOR_MENTOR_STARTUPS_PER_WEEK
    @num_startups_left = current_user.suggested_relationships('Startup').count
    return if @num_startups_left == 0
    @num_startups_completed = (@total_suggested_startups - @num_startups_left).abs
    @pct_complete = ((@num_startups_completed.to_f / @total_suggested_startups.to_f) * 100).to_i
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_bar_chart.html.haml
- chart_id ||= 'chart'
-# Data should be passed in as a k/v hash, with multiple series in the array, ex: {:categories => ['Traction', Team'], :series => {'Investor' => [23, 4]}, {'Mentor' => [3,5]}}
- data ||= {}
- title ||= ''
- type ||= 'column'
- tooltip_enabled ||= false
- y_tick_interval ||= 1
- y_axis_label ||= 'Number of People'

.chart{:id => chart_id}
:plain
  <script type="text/javascript">
  var chart;
  $(document).ready(function() {
    chart = new Highcharts.Chart({
      chart: {
        renderTo: '#{chart_id}',
        type: '#{type}'
      },
      title: {
        text: '#{title}'
      },
      credits: {
        enabled: false
      },
      xAxis: {
        labels: {
          formatter: function() {
            return this.value;
          }
        },
        categories: [#{data[:categories].map{|k| "'#{k}'" }.join(',')}]
      },
      yAxis: {
        title: {
          text: '#{y_axis_label}'
        },
        labels: {
          formatter: function() {
            return this.value;
          }
        },
        tickInterval: #{y_tick_interval}
      },
      plotOptions: {
        area: {
            stacking: 'normal',
            lineColor: '#666666',
            lineWidth: 1,
            marker: {
                lineWidth: 1,
                lineColor: '#666666'
            }
        },
        column: {
          pointPadding: 0.2,
          borderWidth: 1
        }
      },
      tooltip: {
        enabled: #{tooltip_enabled}
      },
      legend: {
        layout: 'horizontal',
        align: 'left',
        verticalAlign: 'top',
        x: 50,
        y: 50,
        floating: true,
        borderWidth: 1,
        backgroundColor: '#FFFFFF',
        shadow: true
      },
      series: #{data[:series].map{|k,v| {'name' => k, 'data' => v } }.to_json}
    });
  });
  </script>

app/views/ratings/_fields.html.haml
= f.hidden_field :startup_id
= f.hidden_field :interested

/ Display any errors for startup
.control-group{error_css(f.object, :startup_id)}
  .controls= f.semantic_errors :startup_id

.control-group{error_css(f.object, :weakest_element)}
  %p What is the weakest element of this startup?
  .controls{:align => 'center'}
    = f.hidden_field :weakest_element, :class => 'weakest_element_hidden_field'
    .btn-group.inline-block{'data-toggle' => 'buttons-radio'}
      - Rating.weakest_element_labels.each do |id, value|
        %button.btn.btn-large.weakest_element{:type => 'button', :rel => id}= value
    %p{:style => 'font-size: 1.1em'} (the biggest blocker to them being fundable)
%br/

.control-group{error_css(f.object, :explanation)}
  %p Please share your feedback with the startup to help them build a better business:
  .controls
    = f.text_area :explanation, :size => '140x5', :class => 'span6'
    = f.semantic_errors :explanation  
    %p{:style => 'font-size: 1.1em;'}
      This will be shared
      %strong anonymously
      with the startup.
      %br/
      If they find it useful they can give you a "#{Awesome.label_for_type('Rating')}" to thank you.

%br/
.control-group{error_css(f.object, :contact_in)}
  %p When would you be interested in meeting with this startup?
  .controls{:align => 'center'}
    = f.hidden_field :contact_in, :class => 'contact_in_hidden_field'
    .btn-group.inline-block{'data-toggle' => 'buttons-radio'}
      - Rating.contact_in_labels.each do |id, desc|
        - css_class = f.object.contact_in.blank? ? 'disabled' : ''
        - css_class += ' btn-danger' if id == 1
        - css_class += ' btn-success' if id == 5
        %button.btn.btn-large.contact_in{:type => 'button', :rel => id, :class => css_class}= desc
    %br/
    - Rating.contact_in_labels(true).each do |id, desc|
      .contact_in_description.inline-block= desc

app/views/ratings/_form.html.haml
= semantic_form_for [@startup, @rating], :remote => true, :html => {:class => 'form-vertical' } do |f|
  = render 'ratings/fields', :f => f
  %br/
  - if f.object.contact_in.blank?
    = f.submit 'Save & Stop', :class => "btn btn-large disabled", :disabled => true
    &nbsp;&nbsp;
    = f.submit 'Save & See Next Startup', :class => "btn btn-large btn-success disabled", :disabled => true
  - else
    = f.submit 'Save & Stop', :class => "btn btn-large"
    &nbsp;&nbsp;
    = f.submit 'Save & See Next Startup', :class => "btn btn-large btn-success"

app/views/ratings/_pie_chart.html.haml
- chart_id ||= 'chart'
-# Data should be passed in as an array of arrays, ex: [['Traction', 23], ['Team', 3]]
- data ||= []
- title ||= ''
.chart{:id => chart_id}
:plain
  <script type="text/javascript">
  var chart;
  $(document).ready(function() {
    chart = new Highcharts.Chart({
      chart: {
        renderTo: '#{chart_id}'
      },
      title: {
        text: '#{title}'
      },
      credits: {
        enabled: false
      },
      legend: {
        enabled: false
      },
      plotOptions: {
        pie: {
          allowPointSelect: true,
          cursor: 'pointer',
          dataLabels: {
            enabled: true,
            color: '#000000',
            connectorColor: '#000000',
            formatter: function() {
              return '<b>'+ this.point.name +'</b>: '+ this.percentage +' %';
            }
          }
        }
      },
      tooltip: {
        enabled: false
      },
      series: [{
      type: 'pie',
      name: '#{title}',
      data: [
        #{data.map{|label, value| "['#{label}', #{value}]" }.join(',')}
        ]
      }]
    });
  });
  </script>

app/views/ratings/_startup.html.haml
.row
  - unless @ratings.blank?
    .span6
      %h3 Aggregated feedback from #{@ratings.size} investor &amp; mentors:
      = render 'ratings/bar_chart', :chart_id => 'weakest_element', :data => @weakest_element_data, :title => 'Biggest aspect holding you back from investors funding you'
      %br/
      = render 'ratings/bar_chart', :chart_id => 'contact_in', :data => @contact_in_data, :title => 'When investors are interested in following up with you'

  .span6
    - if @ratings.blank?
      You haven't been reviewed by any investors or mentors yet.
    - else
      - @ratings.each do |r|
        - if r.interested?
          .right
            - relationship = r.startup_relationship
            - unless relationship.blank?
              = link_to 'Ignore', reject_relationship_path(relationship, :rating_id => r.id), :class => 'btn', :method => :post
              &nbsp;&nbsp;
              = link_to 'Connect', approve_relationship_path(relationship, :rating_id => r.id), :class => 'btn btn-success', :method => :post
          .left
            %h3 #{r.user.name} would like to connect with you.
          .clear
        - else
          %h3 Anonymous #{r.user.mentor? ? 'Mentor' : 'Investor'} saw you #{distance_of_time_in_words_to_now(r.created_at)} ago
          .left
            %strong Result:
            - if r.contact_never?
              Passed
            - else
              Wants to check back in #{r.contact_in_desc}
          .left{:style => 'margin-left: 10px'}
            %strong Main Blocker:
            #{r.weakest_element_desc}
          .clear
          - if r.explanation.present?
            %strong Suggestion:
            %h3 #{simple_format(h(r.explanation))}
            .right!= render_awesome_button(r)
            .right{:style => 'font-size: .85em; margin-right: 10px;', :align => 'right'}
              Did this feedback help your startup?
              %br/
              %small Thank the #{r.user.mentor? ? 'mentor' : 'investor'} by giving them a "#{Awesome.label_for_type('Rating')}"
            .clear
        %hr{:style => 'margin: 10px 0 10px 0'}/

app/views/ratings/edit.js.haml
:plain
  $('form.rating').replaceWith("#{escape_javascript(render('ratings/form'))}");
  $('form.rating textarea').autosize();

app/views/ratings/entrepreneur.html.haml
.board_room
  - if @startup_elements.present?
    .entry_page
      .row
        .span4{:align => 'center'}
          .box.nstar= image_tag 'nstar_m.png', :style => 'width: 230px; height: 195px'
          %h3 Compete to Become an #{link_to 'nStar', nstar_path}
        .span4{:align => 'center'}
          .box.mentors
            .number= @num_mentors
            and counting...
          %h3 Get Help From nReduce Mentors
        .span4{:align => 'center'}
          .box.investors
            Coming Soon
          %h3 Get Feedback From Investors
      %br/
      %br/
      %hr/
      %br/
      %br/
      .row
        %center
          %h2
            To Enter the Board Room
          %br/
          %br/
      .row
        .span1
          %p
        .span5
          %h2 1) Complete the Following Elements
          .startup_elements!= format_profile_elements(@startup_elements)
        .span1
          %p
        .span5
          %h2 2) Submit a Before & After Video Last Week
          .checkin
            - if @previous_checkin.present?
              .week= @previous_checkin.time_label
              .right.after
                After
                - if @previous_checkin.after_completed?
                  .completed &#x2713;
                - else
                  .incomplete &#x2717;
              .left.before
                Before
                - if @previous_checkin.before_completed?
                  .completed &#x2713;
                - else
                  .incomplete &#x2717;
              .clear
            - else
              .week (none)

        
  - else
    .investors
      .startup
        = form_for current_user.startup, :url => '/startup/', :remote => true, :html => {:class => 'form-vertical startup'} do |f|
          = hidden_field_tag 'dont_render_form', true
          .row
            .span4
              %p
            .span4.center
              %h1
                %small Board Room
            .span4
              .right{:style => 'margin: 15px 0px 20px 0px'}
                .left
                  %h3 Seeking Investment
                .left{:style => 'margin-left: 10px'}
                  = f.check_box :investable, :class => 'investable'
                .clear
                %br/
                .left
                  %h3 Seeking Mentorship
                .left{:style => 'margin-left: 10px'}
                  = f.check_box :mentorable, :class => 'mentorable'
                .clear
              .clear
      %hr/
      %br/
      = render 'ratings/startup'

app/views/ratings/new.html.haml
.investors

  = render 'startups/investment_profile'
  %br/

  - unless @checkins.blank?
    = render 'startups/checkins_list', :investor_view => true
    %br/
    %hr/
    %br/

  %center
    = semantic_form_for [@startup, @rating], :remote => true, :html => {:class => 'form-vertical' } do |f|
      = render 'ratings/fields', :f => f
      %br/
      = f.submit 'Save & Stop', :class => 'btn btn-large disabled', :disabled => true
      &nbsp;&nbsp;
      = f.submit 'Save & See Next Startup', :class => 'btn btn-large btn-success disabled', :disabled => true

  %div{:align => 'center'}
    .progress{:style => 'width: 40%', :align => 'left', :title => "#{@pct_complete}% complete"}
      .bar{:style => "width: #{@pct_complete}%"}

  #rating_modal.hide